b13/container

Configuration/TCA/Overrides/tt_content.php, ext_localconf.php
=> [TASK] call_user_func wrap and TYPO3_MODE-checks #6 #7

Classes/Command/IntegrityCommand.php, Configuration/Commands.php
=> [TASK] rename integrity command #2

Classes/Hooks/UsedRecords.php, Classes/Integrity/Integrity.php, Classes/Tca/Registry.php, Classes/View/ContainerLayoutView.php, Tests/Unit/Hooks/UsedRecordsTest.php
=> [BUGFIX] use container depended colPos name #4

README.md
=> [TASK] Fix code examples in README file

Classes/Tca/Registry.php, README.md
=> [TASK] minimize registry parameter by reordering #5

Classes/Tca/Registry.php, README.md
=> [FEATURE] saveAndClose container in new content element wizard #24

.gitattributes
=> [TASK] add .gitattribute file for excluding files on archive #3

Classes/DataProcessing/ContainerProcessor.php, README.md
=> [FEATURE] Generalize DataProcessor #27

Classes/Domain/Factory/Database.php
=> [BUGFIX] use FrontendRestrictionContainer for FE Queries

Classes/Domain/Factory/ContainerFactory.php
=> [TASK] use GeneralUtility::makeInstance for Container instantiation #11

Classes/Tca/Registry.php, README.md
=> [FEATURE] add a default showitem configuration to container #23

Classes/Tca/Registry.php
As with other showitem default values this adds the same configuration used by the "divider" element in core.
Resolves: #41
=> [TASK] Add header field to default showitem configuration

Classes/Tca/Registry.php
=> [TASK] Add deprecated info to registerContainer method

README.md
- Add proper syntax highlighting
- Wrap example correctly
=> [DOC] Improve readme

Classes/ContentDefender/Form/FormDataProvider/TcaCTypeItems.php, Classes/ContentDefender/Hooks/WizardItems.php, Classes/Domain/Factory/ContainerFactory.php, Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php, Classes/Hooks/Datahandler/DatamapAfterDatabaseOperationHook.php, Classes/Hooks/Datahandler/DatamapBeforeStartHook.php, Classes/Integrity/Error/UnusedColPosWarning.php, Classes/Tca/ItemProcFunc.php, Classes/View/ContainerLayoutView.php, Configuration/TCA/Overrides/tt_content.php, ext_localconf.php
- Fix typos
- Use static calls
- Improve doc blocks
=> [TASK] Improve code

composer.json
=> [BUGFIX] update testing-framework package

README.md, Resources/Public/Icons/container-1col.svg, Resources/Public/Icons/container-2col-left.svg, Resources/Public/Icons/container-2col-right.svg, Resources/Public/Icons/container-2col.svg, Resources/Public/Icons/container-3col.svg, Resources/Public/Icons/container-4col.svg, ext_localconf.php
=> [TASK] Provide default icons for multi column containers

Classes/Hooks/UsedRecords.php, Classes/Tca/ItemProcFunc.php
=> [BUGFIX] cast integer #51

Classes/View/ContainerLayoutView.php
=> [BUGFIX] variables access level v9 #53

Classes/View/ContainerLayoutView.php, ext_localconf.php
=> [BUGFIX] v9 PageLayoutView #57

Configuration/TCA/Overrides/tt_content.php, Tests/Functional/Datahandler/Localization/LocalizeTest.php, Tests/Functional/Fixtures/tt_content_default_language_second_container.xml
=> [BUGFIX] remove copyAfterDuplFields TCA Configuration #59

Classes/ContentDefender/Hooks/CommandMapHook.php, Classes/ContentDefender/Hooks/DatamapHook.php
=> [TASK] improve content_defender error message #61

README.md
=> [BUGFIX] wrong examples in README

.gitattributes, .github/workflows/ci.yml, .gitignore, Build/LocalConfiguration.php, Build/envs/.env.github, Build/envs/.env.local, README.md, Resources/Private/Configuration/phpstan.neon, Tests/Acceptance/Backend/EditorLayoutCest.php, Tests/Acceptance/Backend/LayoutCest.php, Tests/Acceptance/Backend/WorkspaceCest.php, Tests/Acceptance/Support/BackendTester.php, Tests/Acceptance/_envs/github.yml, Tests/Acceptance/_envs/local-headless.yml, Tests/Acceptance/_envs/local.yml, Tests/README.md, Tests/codeception.yml, composer.json
=> [FEATURE] use github actions

Classes/ContentDefender/Form/FormDataProvider/TcaCTypeItems.php, Classes/ContentDefender/Hooks/CommandMapHook.php, Classes/ContentDefender/Hooks/DatamapHook.php, Classes/ContentDefender/Hooks/WizardItems.php, Classes/Hooks/ContentDefender/ColumnConfigurationManipulationHook.php, Classes/Hooks/ContentDefender/CommandMapHook.php, Classes/Hooks/ContentDefender/DatahandlerStorage.php, Classes/Hooks/ContentDefender/DatamapHook.php, Classes/Tca/Registry.php, README.md, Tests/Functional/Datahandler/ContentDefender/DefaultLanguageTest.php, Tests/Functional/Fixtures/tt_content_content_defender.xml, composer.json, ext_localconf.php
=> [FEATURE] content_defender integration

Classes/Tca/ContainerConfiguration.php, Classes/Tca/Registry.php, README.md
=> [TASK] container configuration object

Classes/Xclasses/RecordLocalizeSummaryModifier.php, Tests/Unit/Xclasses/RecordLocalizeSummaryModifierTest.php
=> [BUGFIX] Rebuild Columns for Localize Summary

Resources/Public/Icons/container-2col-right.svg, Resources/Public/Icons/container-3col.svg
=> [TASK] Replace transparent icons

Classes/DataProcessing/ContainerProcessor.php, Tests/Functional/Fixtures/Workspace/container_with_ws_child.xml, Tests/Functional/Frontend/WorkspaceTest.php
=> [BUGFIX] Workspace Preview

Classes/DataProcessing/ContainerProcessor.php, Classes/Domain/Factory/ContainerFactory.php, Classes/Domain/Factory/Database.php, Classes/Domain/Factory/PageView/Backend/ContainerFactory.php, Classes/Domain/Factory/PageView/Backend/ContentStorage.php, Classes/Domain/Factory/PageView/ContainerFactory.php, Classes/Domain/Factory/PageView/ContentStorage.php, Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php, Classes/Domain/Factory/PageView/Frontend/ContentStorage.php, Classes/Domain/Model/Container.php, Classes/View/ContainerLayoutView.php, Tests/Functional/Domain/Factory/Fixture/movedChildrenInWorkspaceAjax.xml, Tests/Functional/Domain/Factory/PageView/Backend/ContainerFactoryTest.php, Tests/Functional/Domain/Factory/PageView/Backend/ContentStorageTest.php, Tests/Functional/Fixtures/Workspace/container_moved_to_other_page.xml, Tests/Functional/Fixtures/Workspace/container_with_ws_child_moved_from_outside.xml, Tests/Functional/Fixtures/Workspace/localized_container_moved_to_other_page.xml, Tests/Functional/Fixtures/Workspace/localized_pages.xml, Tests/Functional/Fixtures/Workspace/other_page.xml, Tests/Functional/Fixtures/Workspace/root_page.xml, Tests/Functional/Frontend/WorkspaceTest.php
=> [BUGFIX] ContainerFactories for PageViews

Classes/Xclasses/RecordLocalizeSummaryModifier.php, Tests/Functional/Xclasses/Fixtures/two_container_elements.xml, Tests/Functional/Xclasses/RecordLocalizeSummaryModifierTest.php
=> [BUGFIX] fetch all container uids for record localization

Classes/Hooks/Datahandler/CommandMapPostProcessingHook.php, Tests/Functional/Datahandler/DefaultLanguage/ContainerTest.php
=> [BUGFIX] copy container after element on other page

Classes/DataProcessing/ContainerProcessor.php
=> [FEATURE] allow children to be processed by DataProcessors

.github/workflows/ci.yml, Build/LocalConfiguration.php, Classes/Backend/Grid/ContainerGridColumn.php, Classes/Backend/Grid/ContainerGridColumnItem.php, Classes/Backend/Preview/ContainerPreviewRenderer.php, Classes/Tca/Registry.php, Resources/Private/Partials/PageLayout/Grid/Column.html, Resources/Private/Partials/PageLayout/Record.html, Resources/Private/Templates/Grid.html, Tests/Acceptance/Backend/EditorLayoutCest.php, Tests/Acceptance/Backend/LayoutCest.php, ext_localconf.php
=> [TASK] fluid page module support for BE

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php, Tests/Functional/Datahandler/DefaultLanguage/CopyElementClipboardOtherPageTest.php, Tests/Functional/Datahandler/DefaultLanguage/CopyElementClipboardTest.php, Tests/Functional/Datahandler/DefaultLanguage/MoveElementClipboardOtherPageTest.php, Tests/Functional/Datahandler/DefaultLanguage/MoveElementClipboardTest.php, Tests/Unit/Hooks/Datahandler/CommandMapBeforeStartHookTest.php
happens when you paste CE after by clicking the context menu
of the CE where to paste
=> [BUGFIX] simple cmdmap

Classes/Domain/Factory/Database.php, Classes/Domain/Factory/PageView/ContentStorage.php, Classes/Domain/Factory/PageView/Frontend/ContentStorage.php, Classes/Domain/Factory/PageView/Frontend/LegacyContentStorage.php, Classes/Listener/PageTsConfig.php, Classes/Tca/Registry.php, Classes/View/ContainerLayoutView.php, Configuration/Services.yaml, Resources/Private/Configuration/phpstan11.neon, Tests/Acceptance/Support/Extension/BackendContainerEnvironment.php, Tests/Functional/Datahandler/ContentDefender/CopyContainerTest.php, Tests/Functional/Datahandler/ContentDefender/DefaultLanguageTest.php, Tests/Functional/Datahandler/ContentDefender/LocalizationTest.php, Tests/Functional/Datahandler/DatahandlerTest.php, Tests/Functional/Datahandler/Workspace/ContainerTest.php, Tests/Functional/Domain/Factory/Fixture/10/copiedChildrenInWorkspace.xml, Tests/Functional/Domain/Factory/Fixture/10/movedChildrenInWorkspaceClipboard.xml, Tests/Functional/Domain/Factory/Fixture/10/movedChildrenInWorkspaceSorting.xml, Tests/Functional/Domain/Factory/Fixture/10/movedChildrenInWorkspaceWithTranslation.xml, Tests/Functional/Domain/Factory/Fixture/copiedChildrenInWorkspace.xml, Tests/Functional/Domain/Factory/PageView/Backend/ContainerFactoryTest.php, Tests/Functional/Fixtures/Workspace/10/container_moved_to_other_page.xml, Tests/Functional/Fixtures/Workspace/10/localized_container_moved_to_other_page.xml, Tests/Functional/Fixtures/Workspace/other_page.xml, Tests/Functional/Frontend/WorkspaceTest.php, Tests/Unit/Hooks/Datahandler/DatamapBeforeStartHookTest.php, composer.json, ext_emconf.php, ext_localconf.php
=> [FEATURE] prepare for v11

Tests/Functional/Fixtures/Templates/Image.html, Tests/Functional/Fixtures/TypoScript/data_processor_with_irre.typoscript, Tests/Functional/Fixtures/data_processor_with_irre.xml, Tests/Functional/Frontend/DataProcessorWithIrreTest.php
Relates to: [BUGFIX] Translations of nested content elements
=> [TASK] provide test for irre ce

Classes/Backend/Grid/ContainerGridColumn.php, Tests/Acceptance/Backend/LayoutCest.php, Tests/Acceptance/Fixtures/pages.xml, Tests/Acceptance/Fixtures/tt_content.xml
=> [BUGFIX] Fix Column Title for different containers

Classes/Backend/Preview/ContainerPreviewRenderer.php, Resources/Private/Partials/PageLayout/Record.html, Resources/Private/Templates/Grid.html
=> [BUGFIX] Check whether default record directory exists

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php
=> [BUGFIX] Cast target uid to int prior to further processing

Build/testing-docker/docker-compose.yml, Classes/Listener/PageTsConfig.php, Tests/Acceptance/Backend/InfoModuleCest.php, Tests/Acceptance/Support/Extension/BackendContainerEnvironment.php, composer.json
=> [BUGFIX] add TSconfig to default

Tests/Functional/Tca/RegistryTest.php
=> [TASK] provide Registry Tests for TSConfig

.gitignore, Build/Scripts/runTests.sh, Build/phpunit/FunctionalTests.xml, Build/phpunit/FunctionalTestsBootstrap.php, Build/phpunit/UnitTests.xml, Build/phpunit/UnitTestsBootstrap.php, Build/testing-docker/docker-compose.yml
Have local phpunit .xml and bootstrap files as
suggested by testing-framework.
=> [TASK] Local phpunit setup files

Build/testing-docker/docker-compose.yml, composer.json
=> [BUGFIX] drop fluid-styled-content dependency

Tests/Functional/Fixtures/data_processor_with_data.xml, Tests/Functional/Fixtures/data_processor_with_files.xml, Tests/Functional/Frontend/DataProcessorWithDataTest.php, Tests/Functional/Frontend/DataProcessorWithFilesTest.php
=> [TASK] provide more dataproccessor tests

Classes/Backend/Preview/ContainerPreviewRenderer.php, Classes/Tca/ContainerConfiguration.php, Classes/Tca/Registry.php, README.md
=> Configure grid partial paths

Classes/Domain/Factory/Database.php, Classes/Domain/Factory/PageView/ContainerFactory.php, Tests/Functional/Fixtures/Workspace/container_in_ws_whith_hidden_live_version.xml, Tests/Functional/Frontend/WorkspaceTest.php, Tests/Unit/Domain/Factory/PageView/ContainerFactoryTest.php
remove all querybuilder restriction when fetch one record by uid
Fix: #184
=> [BUGFIX] querybuilder restrictions

Classes/ContentDefender/Hooks/DatamapHook.php, Classes/DataProcessing/ContainerProcessor.php, Classes/Tca/Registry.php
Only checking places that reported errors in v11/PHP8
=> [TASK] Harden array access

Resources/Private/Partials/PageLayout/Record.html
see https://review.typo3.org/c/Packages/TYPO3.CMS/+/71101
=> [TASK] use f:translate viewhelper in grid partials

Resources/Private/Partials/PageLayout/Grid/Column.html, Resources/Private/Templates/Grid.html, Tests/Acceptance/Backend/LayoutCest.php
Small template improvement. Use class t3-grid-cell to visually separate the container areas.
=> [TASK] Highlight grid cell

Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php, Classes/Domain/Factory/PageView/Frontend/ContentStorage.php, Tests/Functional/Fixtures/LanguageFallback/tt_content_both_translated_tranlated_child_hidden.xml, Tests/Functional/Fixtures/LanguageStrict/tt_content_both_translated.xml, Tests/Functional/Fixtures/LanguageStrict/tt_content_both_translated_tranlated_child_hidden.xml, Tests/Functional/Fixtures/LanguageStrict/tt_content_child_translated.xml, Tests/Functional/Fixtures/LanguageStrict/tt_content_container_translated.xml, Tests/Functional/Fixtures/pages.xml, Tests/Functional/Frontend/LanguageFallbackTest.php, Tests/Functional/Frontend/LanguageStrictTest.php
use Core PageRepository to do language overlay of children
=> [BUGFIX] frontend language overlay

Classes/Hooks/ContentDefender/DatamapHook.php
=> [BUGFIX] Avoid PHP 8.0 error in Datamap Hook

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php, Tests/Functional/Datahandler/Localization/LocalizeTest.php
=> [BUGFIX] do not use flash message queue in datahandler

Build/phpstan10.neon, Build/phpstan11.neon
=> [TASK] Remove temporary phpstan entries again

Classes/Tca/ContainerConfiguration.php, Classes/Tca/Registry.php, README.md
With the `setTtContentDefValues` method we can directly set for a given container what it's default values are.
The CType is set by default
=> [FEATURE] Allow the tt_content_defValues to be set for a container

Classes/Hooks/Datahandler/CommandMapPostProcessingHook.php, Classes/Hooks/Datahandler/DatamapBeforeStartHook.php, Tests/Functional/Datahandler/Localization/FreeMode/ContainerTest.php, Tests/Functional/Fixtures/tt_content_translations_free_mode.xml
=> [BUGFIX] copy nested containers to other language

Classes/Backend/Grid/ContainerGridColumn.php, Classes/Backend/Grid/ContainerGridColumnItem.php, Classes/Domain/Model/Container.php, Classes/View/ContainerLayoutView.php, Resources/Private/Partials/PageLayout/Grid/Column.html, Resources/Private/Partials/PageLayout/Record.html, Tests/Acceptance/Backend/WorkspaceCest.php, Tests/Acceptance/Fixtures/pages.xml, Tests/Acceptance/Fixtures/tt_content.xml, Tests/Functional/Backend/Grid/ContainerGridColumnItemTest.php, Tests/Functional/Backend/Grid/ContainerGridColumnTest.php
=> [BUGFIX] use uid of live workspace element for container parent

Classes/Domain/Factory/PageView/Backend/ContentStorage.php, Tests/Functional/Domain/Factory/Fixture/deletedChildInWorkspace.xml, Tests/Functional/Domain/Factory/PageView/Backend/ContentStorageTest.php
=> [BUGFIX] deleted workspace children

Configuration/TCA/Overrides/tt_content.php
=> [BUGFIX] prevent loading of CE in tx_container_parent

Classes/Hooks/Datahandler/DatamapPreProcessFieldArrayHook.php, Tests/Functional/Datahandler/Localization/ConnectedMode/CopyElementTest.php, Tests/Functional/Datahandler/Localization/ConnectedMode/Fixtures/CopyElement/copy_element_after_container.csv, Tests/Functional/Datahandler/Localization/Fixtures/Localize/localize_element_after_already_localized_container.csv, Tests/Functional/Datahandler/Localization/LocalizeTest.php
=> [BUGFIX] sorting of localized elements

Configuration/Icons.php
Also, refactor into a more verbose and simple
form of the returning array.
Fixes: #303
=> [BUGFIX] Add missing "source" key for icon registration

Classes/ContentDefender/Xclasses/DatamapHook.php, Tests/Functional/Datahandler/ContentDefender/Fixtures/Maxitems/can_translate_child_if_container_of_default_language_maxitems_reached.csv, Tests/Functional/Datahandler/ContentDefender/MaxItemsTest.php
=> [BUGFIX] no content defender restriction for localized records

Classes/Hooks/Datahandler/DatamapBeforeStartHook.php, Tests/Functional/Datahandler/Localization/ConnectedMode/CopyElementTest.php, Tests/Functional/Datahandler/Localization/ConnectedMode/Fixtures/CopyElement/copy_element_after_container_with_child.csv
because elements are sorted correct since 2.0
it is now necessary to fix colPos for localized records outside container also
Fixes: #302
=> [BUGFIX] colPos for localized records

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php
=> [BUGFIX] PHP 8 array access

Resources/Private/Language/locallang.xlf
=> [BUGFIX] XLIF File Format

Build/sites/main/config.yaml, Classes/Domain/Factory/PageView/Frontend/ContainerFactory.php, Tests/Functional/Frontend/Fixtures/LanguageFallback/tt_content_fallback_for_strict_language_to_other_translation_free_mode.csv, Tests/Functional/Frontend/LanguageFallbackTest.php
use container language for children in free mode
Fixes: #340
=> [BUGFIX] language fallback

Classes/Listener/PageTsConfig.php
=> [BUGFIX] Strictify PageTsConfig

Classes/Hooks/Datahandler/Database.php
=> Remove starttime and endtime-restriction

Classes/Backend/Preview/ContainerPreviewRenderer.php
assign the original record as containerRecord to view allows modification of the record by PageLayoutViewDrawItemHookInterface or by PageContentPreviewRenderingEvent Listeners
=> [FEATURE] allow containerRecord modification

Classes/DataProcessing/ContainerProcessor.php, Tests/Functional/Frontend/DefaultLanguageTest.php, Tests/Functional/Frontend/Fixtures/TypoScript/setup_skip_rendering_child_content.typoscript
add skipRenderingChildContent Option for ContainerProcessor
Fixes: #156
=> [FEATURE] new DataProcessing Configuration

Classes/ContentDefender/Xclasses/DatamapHook.php, Tests/Functional/Datahandler/ContentDefender/Fixtures/Maxitems/can_save_child_in_default_language_when_translated_and_maxitems_is_reached.csv, Tests/Functional/Datahandler/ContentDefender/MaxItemsTest.php
=> [BUGFIX] maxitems with localized children

Classes/Domain/Model/Container.php
=> [BUGFIX] cast database result integer fields

Tests/Functional/Backend/Grid/ContainerGridColumnItemTest.php, Tests/Functional/Backend/Grid/ContainerGridColumnTest.php, Tests/Functional/Service/RecordLocalizeSummaryModifierTest.php, Tests/Unit/Domain/Factory/PageView/ContainerFactoryTest.php, Tests/Unit/Hooks/Datahandler/CommandMapBeforeStartHookTest.php, Tests/Unit/Hooks/Datahandler/DatamapBeforeStartHookTest.php
=> [TASK] prepare for phpunit 10

Classes/ContentDefender/Xclasses/DatamapHook.php, Tests/Functional/Datahandler/ContentDefender/Fixtures/Maxitems/can_copy_to_language_child_if_container_of_default_language_maxitems_reached.csv, Tests/Functional/Datahandler/ContentDefender/MaxItemsTest.php
=> [BUGFIX] copyToLanguage with maxitems

Classes/Hooks/Datahandler/DeleteHook.php, Tests/Functional/Datahandler/Workspace/ContainerTest.php, Tests/Functional/Datahandler/Workspace/Fixtures/tt_content_container_with_child_in_workspace.csv, Tests/Functional/Datahandler/Workspace/Fixtures/tt_content_container_with_child_in_workspace10.csv
Fixes: #387
Relates: https://forge.typo3.org/issues/100504
=> [BUGFIX] delete container in WS

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php, Tests/Functional/Datahandler/DefaultLanguage/ContainerTest.php, Tests/Functional/Datahandler/DefaultLanguage/Fixtures/Container/move_container_into_itselfs_nested.csv
a container should not be copied or moved inside himself also nested containers should be considered
Relates: #405
Relates: #347
=> [BUGFIX] prevent invalide copy/move cmds

Build/phpstan10.neon, Build/sites/main/config.yaml, Classes/DataProcessing/ContainerProcessor.php, Tests/Functional/Frontend/Fixtures/SiteLanguageFree/setup.csv, Tests/Functional/Frontend/SiteLanguageFreeTest.php
=> [BUGFIX] siteLanguage with fallbackType free

Classes/Domain/Factory/ContainerFactory.php, Tests/Functional/Datahandler/Workspace/ContainerTest.php, Tests/Functional/Datahandler/Workspace/Fixtures/tt_content_deleted_placeholder.csv
=> [BUGFIX] deleted children in workspace

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php, Classes/Hooks/Datahandler/DatamapPreProcessFieldArrayHook.php, Classes/Integrity/Database.php, Classes/Integrity/Sorting.php, Tests/Functional/Datahandler/DefaultLanguage/ContainerTest.php, Tests/Functional/Datahandler/DefaultLanguage/Fixtures/Container/copy_container_keeps_sorting.csv, Tests/Functional/Datahandler/DefaultLanguage/Fixtures/MoveElement/nested_container.csv, Tests/Functional/Datahandler/DefaultLanguage/Fixtures/NewElement/nested_container.csv, Tests/Functional/Datahandler/DefaultLanguage/MoveElementOtherPageTest.php, Tests/Functional/Datahandler/DefaultLanguage/MoveElementTest.php, Tests/Functional/Datahandler/DefaultLanguage/NewElementTest.php, Tests/Functional/Integrity/Fixtures/Sorting/nested_container.csv, Tests/Functional/Integrity/SortingTest.php, Tests/Functional/Integrity/SortingWithContentDefenderTest.php
=> [BUGFIX] sorting with nested containers

Build/testing-docker/docker-compose.yml
set php-cs-fixer for v12 to ~3.26.1
=> fix php-cs-fixer version

Classes/Hooks/Datahandler/CommandMapPostProcessingHook.php
we cannot sure, datahandler pass an integer
as id to our method
=> [BUGFIX] change id parameter to mixed

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php
=> [BUGFIX] cast to int

Classes/Tca/ItemProcFunc.php
=> [BUGFIX] Check existence to avoid notices

Classes/Domain/Factory/Database.php
['TYPO3_REQUEST'] is a ?ServerRequestInterface
=> [BUGFIX] use interface in return type decleration

Classes/Tca/ContainerConfiguration.php
=> [BUGFIX] remove backendTemplate from ContainerConfiguration

Classes/Listener/ContentUsedOnPage.php
=> [BUGFIX] Prevent ContentUsedOnPage listener to "unhide" content elements

README.md
=> [BUGFIX] Improve spelling in README.md

Configuration/Services.yaml
=> [FEATURE] Add alias for container data processor

Build/Scripts/runTests.sh, Build/phpstan-baseline-11-7.4.neon, Build/phpstan11-7.4.neon, Classes/Updates/ContainerDeleteChildrenWithWrongPid.php, Classes/Updates/ContainerMigrateSorting.php, ext_localconf.php
* do not register upgrade wizards if EXT:install is not installed
* use PHP Attributes for upgrade wizards
* adapt phpstan
Fixes. #525
=> [BUGFIX] upgrade wizards

Classes/Tca/Registry.php, Tests/Acceptance/Backend/LayoutCest.php
=> [BUGFIX] description of container in new CE wizard

Resources/Private/Partials/PageLayout/Grid/Column.html
=> [BUGFIX] container parent data attribute for js

ext_localconf.php
for TYPO3 > 11 PHP Attributes are used
Relates to: #549
=> [BUGFIX] update wizards registration

Tests/Functional/Tca/RegistryTest.php
=> [TASK] test for issue 542

Classes/Domain/Factory/Database.php, Tests/Functional/Frontend/Fixtures/Workspace/child_in_ws_whith_hidden_live_version.csv, Tests/Functional/Frontend/WorkspaceTest.php
=> [BUGFIX] Workspace version of hidden child

Classes/Domain/Factory/FrontendContainerFactory.php, Tests/Functional/Frontend/DefaultLanguageTest.php, Tests/Functional/Frontend/Fixtures/ContainerWithTwoChildren.csv, Tests/Functional/Frontend/Fixtures/Templates/ContainerWithTwoChildren.html, Tests/Functional/Frontend/Fixtures/TypoScript/container_with_two_children.typoscript
=> [BUGFIX] container children sorting

Classes/Hooks/Datahandler/CommandMapBeforeStartHook.php, Tests/Acceptance/Backend/ContentDefenderCest.php, Tests/README.md
* Datahandlers log method changed method annotations 
* Context Menu Accessibility has been improved
=> [TASK] make CI happy with TYPO3 13.4.5

Classes/ContentDefender/Xclasses/DatamapHook.php, Tests/Functional/Datahandler/ContentDefender/DefaultLanguageTest.php, Tests/Functional/Datahandler/ContentDefender/Fixtures/DefaultLanguage/CopyContentElementIntoContainerWhenCTypeIsNotAllowedInBackendLayoutColumn.csv, Tests/Functional/Datahandler/ContentDefender/Fixtures/DefaultLanguage/CopyContentElementIntoContainerWhenCTypeIsNotAllowedInBackendLayoutColumnResult.csv
=> [BUGFIX] can copy into container

Classes/Hooks/Datahandler/CommandMapPostProcessingHook.php, Tests/Functional/Datahandler/DefaultLanguage/ContainerTest.php
=> [BUGFIX] copy container
